services:
  user_credential_pg:
    image: postgres
    container_name: user_credential_pg
    environment:
      POSTGRES_DB: user_credential_db
      POSTGRES_USER: user_credential_db_user
      POSTGRES_PASSWORD: master
    volumes:
      - ./entrypoint:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  mongo:
    ports:
      - '27017:27017'
    container_name: dkrcomp-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    image: mongo