services:
  postgres:
    image: debezium/postgres:16
    container_name: user_credential_pg
    environment:
      POSTGRES_DB: user_credential_db
      POSTGRES_USER: user_credential_db_user
      POSTGRES_PASSWORD: master
    volumes:
      - ./entrypoint:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

#  kafka:
#    image: confluentinc/cp-kafka:7.3.0
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    depends_on:
#      - zookeeper
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.3.0
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#
#  connect:
#    image: debezium/connect:2.1
#    ports:
#      - "8083:8083"
#    environment:
#      GROUP_ID: 1
#      CONFIG_STORAGE_TOPIC: my_connect_configs
#      OFFSET_STORAGE_TOPIC: my_connect_offsets
#      STATUS_STORAGE_TOPIC: my_connect_statuses
#      BOOTSTRAP_SERVERS: kafka:29092
#    depends_on:
#      - kafka
#      - postgres

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
#    ports:
#      - "9200:9200"
#    environment:
#      - discovery.type=single-node
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m

#  mongo:
#    ports:
#      - '27017:27017'
#    container_name: dkrcomp-mongo
#    restart: always
#    logging:
#      options:
#        max-size: 1g
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=pass
#    image: mongo